### ISSUE TITLE
REPLIT deployment problem

### ISSUE THREAD

**Issue by PotatoWatch** [QuiteAFancyEmerald/HolyUnblockerPublic#171]
I cloned the Replit repo using the link in the README.md and did all the config without changing anything (clicked the OK button for the language = nodejs and start = npm start). When I ran it immediately  afterwards, it gave me this error:

```
> node app.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/runner/HolyUnblockerPublic/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/HolyUnblockerPublic/app.js:12:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/HolyUnblockerPublic/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! holyub@4.8.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the holyub@4.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-05T21_53_40_768Z-debug.log
exit status 1
```
What?

**Comment by Nebelung-Dev** [comment]
try running npm install in the console

**Comment by Adithr123** [comment]
THanks

**Comment by PotatoWatch** [comment]
> try running npm install in the console

Okay. Ill try!

**Comment by Nebelung-Dev** [comment]
did that fix it?

**Comment by Adithr123** [comment]
Yes.

**Comment by PotatoWatch** [comment]
Yeah. Proxies don't work (i think something else needs to be done about it - its fine). At least it loads properly!

**Comment by Nebelung-Dev** [comment]
Womginx and PyDodge need there own servers

**Comment by PotatoWatch** [comment]
Okay.
